"""initial_schema

Revision ID: fdd0d88e5d34
Revises: fb7e860508b1
Create Date: 2025-12-16 18:28:59.372705

"""

from typing import Sequence, Union

# trunk-ignore(ruff/F401)
import sqlalchemy as sa

# trunk-ignore(ruff/F401)
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdd0d88e5d34"
down_revision: Union[str, Sequence[str], None] = "fb7e860508b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
